### ISSUE TITLE
please publish 1.1.1 due to security vulnerability

### ISSUE THREAD

**Issue by daniel-seitz** [browserify/vm-browserify#26]
Dear package maintainers,

we have an up-to-date angular application in production which indirectly references this package (webpack -> node-libs-browser -> vm-browserify). However we still find the old jQuery as a security vulnerability.

I understand this is a dev-dependency, however as that was already resolved this year in January in https://github.com/browserify/vm-browserify/commit/27cf2ff89601bd83457f2e9172eb3132b9c08f4e it would be great to get v1.1.1 with this change.

Thank you,
Daniel

**Comment by goto-bus-stop** [comment]
done, thanks for the reminder!

**Comment by daniel-seitz** [comment]
@goto-bus-stop wow, that was ninja-like, so fast, I didnt see it coming :)
Thank you!
